#!/usr/bin/env perl

#hull形式に含まれる多角形を、hull2povが処理しやすいように三角形分割する。
#オプションなどはない。

die "usage: $0 < infile.hull > outfile.hull\nDivide polygons into a set of triangles.\n" if($#ARGV>=0);

while(<STDIN>){
    s/#.*$//;
    split;
    next if($#_==0);
    ($r,$g,$b)=@_;
    $rgb="$r $g $b";
#skip empty lines
    do{
	$_=<STDIN>;
	s/#.*$//;
    }while ($_ =~ /^ *$/);
    $n=0;
    $s="";
    while($_ !~ /^ *$/){
	$line[$n]=$_;
	$n++;
	if($n==3){
	    print "$rgb\n\n";
	    print @line;
	    print "\n";
	    $line[1]=$line[2];
	    $n--;
	}
	$_=<STDIN>;
    }
}

close(FILE);
0;
